# Generated by Django 3.2.5 on 2021-07-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="summary",
            field=models.TextField(default="Summary not available."),
            preserve_default=False,
        ),
    ]
